use_frameworks!

platform :ios, '9.0'

target 'AWLogging_Example' do
  pod 'AWLogging', :path => '../'

  target 'AWLogging_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
